serv:
  build: .
  volumes:
    - .:/root
    - ./lib/sign/target/release/sign:/root/sign
    - ./keys/pub.pem:/root/public/static/pub.pem
  working_dir: /root
  command: bash -c 'php -S 0.0.0.0:8000 -t /root/public'
  ports:
    - 8000:8000
  environment:
    - RUST_BACKTRACE=1
