serv:
  build: .
  volumes:
    - ./public:/root/public
    - ./templates:/root/templates
    - ./db.sqlite3:/root/db.sqlite3
    - ./credentials.json:/root/credentials.json
    - ./lib/sign/target/release/sign:/root/sign
    - ./keys/pri.pem:/root/pri.pem
    - ./keys/pub.pem:/root/public/static/pub.pem

  working_dir: /root
  command: bash -c 'php -S 0.0.0.0:8000 -t /root/public'
  ports:
    - 8000:8000
  environment:
    - RUST_BACKTRACE=1
