serv:
  build: .
  volumes:
    - ./public:/root/public
    - ./templates:/root/templates
    - ./db.sqlite3:/root/db.sqlite3
    - ./credentials.json:/root/credentials.json
  working_dir: /root
  command: bash -c 'php -S 0.0.0.0:8000 -t /root/public'
  ports:
    - 8000:8000
