version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api:/root
    working_dir: /root
    command: bash -c 'php -S 0.0.0.0:8001 -t /root/public'
    ports:
      - 8001:8001

  app:
    image: python:3
    volumes:
      - ./app:/root
    working_dir: /root
    command: bash -c 'python3 -m http.server 8000'
    ports:
      - 8000:8000
